### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by nomimalik1769** [pmusolino/Wormholy#6]
Not Working properly on iPhone 5s Layout design issue I am Unable to Read full details
![image](https://user-images.githubusercontent.com/26509387/42870377-24cbace4-8a91-11e8-833a-c08a45202ab7.png)

**Comment by pmusolino** [comment]
Hi @nomimalik1769 
I solve it as soon as possible.

Thanks
-Paolo

**Comment by pmusolino** [comment]
Fixed in this new release 
<img width="569" alt="schermata 2018-07-18 alle 11 38 00" src="https://user-images.githubusercontent.com/495617/42873361-20840382-8a7f-11e8-8479-70042655ff70.png">

**Comment by nomimalik1769** [comment]
**Issue is still the same. I have updated the Pod and the problem is still their.**
![image](https://user-images.githubusercontent.com/26509387/42989226-9c2269bc-8c18-11e8-9052-e4c5fd3ba103.png)

**Comment by pmusolino** [comment]
Are you sure that you call, before the pod update, `pod repo update`?

**Comment by nomimalik1769** [comment]
yes, and I have checked the pod.lock it's on the latest version and the issue is still same. I have deleted the pod and also reinstall it. But the issue is still the same.

**Comment by pmusolino** [comment]
Can you try on iOS 11 if you have the same issue?
